import { SidebarNavigation } from "@/components/shared/SidebarNavigation/SidebarNavigation";
import { Flex } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Providers } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ backgroundColor: "#111827" }}>
        <Providers>
          <Flex>
            <SidebarNavigation />
            <Flex flex="1" ml="180px" justifyContent={"center"} p={4}>
              {children}
            </Flex>
          </Flex>
        </Providers>
      </body>
    </html>
  );
}
